moment/moment

- src/lib/duration/create.js
- src/test/moment/duration.js
> Add duration.fn back

- CONTRIBUTING.md
> Update link to example unit test

- src/lib/units/offset.js
There is unreachable code in function cloneWithOffset().
> Remove unreachable code

- bower.json
- tasks/bump_version.js
Per https://github.com/bower/bower.json-spec/commit/a325da3d79baab018c572d75dc1781b12322f6cd
> bower.json: remove moot `version` field

- .npmignore
Requested in https://github.com/moment/moment/issues/2520
> Ignore min/tests.js from npm package

- src/locale/tlh.js
- src/test/locale/tlh.js
Adds klingon locale, as proposed in Issue #2431. 
Based on some excellent online resources :)
> Adds klingon(tlh) locale

- src/lib/create/from-string.js
- src/locale/gd.js
- src/locale/tzl.js
- src/test/moment/format.js
- src/test/moment/now.js
A few minor corrections to make moment work in IE8.
> Fix broken tests in IE8

- src/locale/ru.js
- src/test/locale/ru.js
#2882
#2569
Вот это вот: http://lh.2xlibre.net/locale/ru_RU/ Неправильная информация (!!!)
Этот PR корректно откатывает сделанный ранее 80fa7c5621797591e81b49c48621f53e858737a5
> Russian locale fixes: punctuation and capital letters

- src/locale/af.js
- src/test/locale/af.js
> Fix Afrikaans March abbr

- ISSUE_TEMPLATE.md
The following is a stab at a default issue template. Feedback welcome.
**Description of the Issue:**
**Expected result:**
**Actual result:**
**Steps and Code to Reproduce the Issue:**
*Please include the values of all variables used.*
**Moment.JS Version:**
**Environment:**
*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*
*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*
**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)
*If you need troubleshooting help, you will probably get a faster response on Stack Overflow*
> moment issue template

- CONTRIBUTING.md
Adds a link to sign CLA, in case contributor wants to sign it immediately.
> Adds "sign CLA" link to `CONTRIBUTING.md`.

- tasks/transpile.js
> Fix #4060: bundle.generate returns a Promise now

- src/lib/moment/diff.js
I think it's easier to read and understand if we switch this block to switch instead of the chained ternary operator. 
Thanks.
> Convert long ternary operator to switch for easier readability

- src/locale/bm.js
- src/test/locale/bm.js
> Add Bambara language (bm)

- src/lib/moment/add-subtract.js
- src/test/moment/duration.js
> [bugfix] Add duration fields in month, day, time order, fixes #3997

- package.json
This reverts commit aea6a97463521ebadae2f0c53536f36768ddee0d.
This seems to be related to https://github.com/moment/moment/issues/4216#issuecomment-335489518
> Revert "jsnext:main -> module (#3904)"

- src/locale/es-us.js
I believe this will fix the button near the bottom of https://momentjs.com. If not, feel free to delete this PR.
> [misc] Fix spelling and formatting for U.S. for es-us 

- component.json
- src/locale/mt.js
- src/test/helpers/common-locale.js
- src/test/locale/mt.js
Months and days names, long and short format, time format for the Maltese Language
> [new locale] mt: Maltese language

- src/locale/es-us.js
- src/test/locale/es-us.js
Simple format change for Spanish - US locale.
> [locale] es-us: Updated time format in accordance with CLDR and www.timeandunits.com

- src/locale/pt-br.js
- src/test/locale/pt-br.js
Just a little shorter version, same meaning
Author, @caio-ribeiro-pereira please verify
> [locale] pt-br: Simplify pt-br past relativeTime

- src/lib/units/hour.js
Nice to have a gender neutral codebase.
> [misc] Make comment in hour.js gender neutral

- moment.d.ts
- typing-tests/moment-tests.ts
> [misc] Add .ts defn for parseTwoDigitYear

- src/locale/ru.js
- src/test/locale/ru.js
> [locale] ru: add a comma to the calendar displays time

- src/lib/units/day-of-month.js
> [misc] fix typo in comment for day-of-month.js

- src/test/moment/start_end_of.js
> [tests] Fix "the the" typo in test

- src/locale/pa-in.js
- src/test/locale/pa-in.js
> [locale] Fix #4568: Insert punjabi for "next" in nextWeek format

- src/locale/pa-in.js
- src/test/locale/pa-in.js
- src/test/moment/start_end_of.js
- src/test/moment/weeks.js
All tests using Feb 29th are labelled as Feb 28th.
> [misc] Typo in test

- src/lib/duration/create.js
- src/locale/sl.js
> [misc] Remove unnecessary ternary spotted by Coverity

- src/locale/en-SG.js
- src/test/locale/en-SG.js
One of my first pull requests!
Grunt tests successfully pass
> [new locale] Added support for en-SG (Singapore)

- src/locale/ga.js
- src/test/locale/ga.js
Fixed some typos in the Irish locale regarding months.
> [locale] Irish locale

- src/locale/br.js
- src/test/locale/br.js
Implementing https://github.com/moment/moment/issues/4974
> [locale] (br) Breton move from 12-hour to 24-hour notation

- FAQ.md
- README.md
* This document is a work in progress and it is used to collect common questions.
* I believe this document can help developers quickly locate and solve some common problems.
> Add FAQ.md

- src/locale/ja.js
> [bugfix] moment#5327 output wrong next week in ja locale

- locale/tet.js
- src/locale/tet.js
- src/test/locale/tet.js
Bugfix for issue [5001](https://github.com/moment/moment/issues/5001)
> [locale] tet: Fix seconds translation

- src/locale/pt-br.js
- src/locale/pt.js
- src/test/locale/pt-br.js
- src/test/locale/pt.js
> [locale] Uncapitalization of pt month names

- src/locale/gom-latn.js
- src/test/locale/gom-latn.js
Corrected an error in the function processRelativeTime for the locale gom-latn and updated tests
> [locale] Correct processRelativeTime for gom-latn

- src/locale/fa.js
- src/test/locale/fa.js
Fixed https://github.com/moment/moment/pull/5005
> %d is correct, not d%
> [locale] fa: Fix typo

- moment.d.ts
Closes https://github.com/moment/moment/issues/5007
> [bugfix] ts: add ts isoWeek support #5007

- Gruntfile.js
- benchmarks/compare.js
- benchmarks/get.js
- benchmarks/set.js
Add grunt benchmark sub tasks: get, set, endOf, startOf, compare
Add grunt benchmark sub task for running all: all
> [misc] Add general benchmarks: get, set, compare (#2659)

- src/locale/eo.js
- src/test/locale/eo.js
Unified Esperanto updates. 
Dankon, @Vivakvo!
Closes #5343
Closes #5455 
Closes #5456
> [locale] eo: corrections

- src/lib/units/year.js
- src/test/moment/format.js
> [bugfix] Change 'Y' format token to adhere to ISO under 9999, fixes #3842

- src/locale/ar-dz.js
- src/test/locale/ar-dz.js
Hello,
This a more accurate localization for ar-dz (Algeria), based on the general Arabic localization (ar).
Hop the original author @nlouahedj approve this :)
> [locale] (ar-dz) improve translation

- locale/tr.js
- src/locale/tr.js
- src/test/locale/tr.js
Meridem is not transalted to turkish.
> [locale] tr: Add meridiem support

- package-lock.json
- package.json
* Import `cross env`,  Fix errors reported by `ts3.1-typescript-test` and `typescript test`  running on windows
* Working well on windows and Mac.
> [tests] Get TS tests working on Windows with cross-env

- composer.json
- package-lock.json
> [pkg] Switch to composer-installers-extender

- ts3.1-typing-tests/moment-tests.ts
- ts3.1-typings/moment.d.ts
- typing-tests/moment-tests.ts
> [bugfix] update moment.d.ts for calendar()

- src/locale/es.js
- src/test/locale/es.js
> [locale] es: fix accent mark

- src/locale/ug-cn.js
Make the comments consistent with the other locale files
fixes https://github.com/moment/moment/issues/5633
> [misc] Update comment in ug-cn.js

- src/lib/moment/calendar.js
- src/test/moment/calendar.js
> [bugfix] allow moment().calendar(undefined)

- moment.d.ts
- ts3.1-typing-tests/moment-tests.ts
- ts3.1-typings/moment.d.ts
- typing-tests/moment-tests.ts
> [bugfix] expose deprecation handler in typings

- README.md
Cleaning up the readme, and highlighting the project status.
> [misc] Updating README

- moment.d.ts
- ts3.1-typings/moment.d.ts
Hi, 
I have added  a 'ww' key to the RelativeTimeSpec Interface & RelativeTimeKey to solve issue #5700. If there are any problems or there is anything else I need to do before this can be merged please let me know. Thanks!
fixes #5700
> [misc] add 'ww' key to RelativeTimeSpec Interface

- .github/ISSUE_TEMPLATE/bug_report.md
this bug report template is very generic and I would like to more changes to it, such as remove the smartphone section and add more fields that are moment specific.
I'm gonna make this a draft for now. Once I get the "go ahead" I will proceed to make it a better bug report template
> [misc] update bug report template

- src/lib/units/month.js
- src/locale/pl.js
- src/test/locale/pl.js
Fixes https://github.com/moment/moment/issues/5369
I've replaced hack with a bit nicer hack :)
> [bugfix] Fixed moment.months() for PL locale

- src/lib/create/from-string-and-array.js
- src/lib/create/from-string-and-format.js
- src/lib/create/from-string.js
- src/lib/duration/valid.js
- src/lib/moment/constructor.js
- src/lib/moment/get-set.js
- src/lib/parse/token.js
- src/lib/utils/deprecate.js
- src/lib/utils/is-moment-input.js
- src/lib/utils/map.js
This pull request will improve the performance as I am pre calculating the array length before the for loop execution
For example
```
let i, arr = [1,2,3,4,5];
for(i = 0; i< arr.length; i++) {
console.log(i)
}
```
arr.length will execute in each iteration which slows our execution. For this I just pre calculate the length and use that variable in each iteration like
```
let i, arr = [1,2,3,4,5], arrLen = arr.length;
for(i = 0; i< arrLen; i++) {
console.log(i)
}
```
I am also attachig the test suite case run time which is decrease by 610ms after changes
Before
After
> [misc] optimize for loops
