moment/moment

src/lib/moment/calendar.js, src/test/moment/format.js
This is useful if you want to override the locale-specified defaults on a case-by-case basis (i.e., not by changing the global config), for example if you don't want to include the time:
moment().calendar(null, {
sameDay: '[Today]',
nextDay: '[Tomorrow]',
nextWeek: 'dddd',
lastDay: '[Yesterday]',
lastWeek: '[Last] dddd'
})
Note that if you don't override a format, the default from the locale is still used - i.e., `sameElse` isn't specified above.
=> Allow custom formats to be passed to calendar function.

tasks/transpile.js
#2367 **moment-with-locales.custom.js uses last defined locale by default**
`moment-with-locales.js` and `moment-with-locales.custom.js` were default to "en".
See grunt task `embedLocales`: 
```javascript
var languageReset = 'moment.locale(\'en\');';
```
Adding it back to transpiling task seems the right thing to do. 
---
**custom locale building was broken**
In current built `moment-with-locales.custom.js`:
this line
```javascript
var moment_with_locales_custom = moment;
```
which `moment` is actually undefined, and should be replaced with the matches from the regex, 
and thus become
```javascript
var moment_with_locales_custom = moment__default;
```
=> Fix building tasks for `moment-with-locales.js` and `moment-with-locales.custom.js`

src/lib/moment/constructor.js, src/test/moment/create.js
This was caused by https://github.com/moment/moment/pull/2368/files#diff-e792da0601bb2705000e86ef203f8e73R61
We should have had a test to cover for this case :)
Fix for #2512
=> Fix constructor regression

README.md
Since `develop` is this repo's default branch and there's no coverage data for master (yet).
=> Coveralls badge should use develop branch

package.json
Dev deps cannot pass with grunt > 0.4
1.0 will fail without deps themselves updating. PEgging the grunt dep
ensures that npm install will work without error
fixes #3091
=> deps: peg grunt to ~0.4

src/lib/locale/base-config.js, src/lib/locale/locales.js, src/lib/locale/prototype.js, src/lib/locale/set.js, src/lib/units/day-of-week.js, src/lib/units/month.js, src/test/helpers/common-locale.js, src/test/moment/locale_inheritance.js, src/test/moment/locale_update.js
Previously english locale was defined mostly in Locale.prototype. Now it's
moved in locale config (similar to all other locales) that is merged the same
way locales are patched (updated).
Fixes #3137 
NOTE: changes in `src/test/helpers/common-locale.js` are because common tests for weekdays were plain wrong -- they weren't iterating all weekdays. It should go in a separate PR, if I'm not lazy.
----
Now the real story: we were depending in a few places that some stuff is just a given (in the prototype).
* monthsParse, weekdaysParse -- assumes that if you have an own property then you define it, otherwise you want the default (esp for strict parsing). Now that it doesn't have prototype the check needs to be revised (I do === DEFAULT), but that is not ideal
* longDateFormat -- we add …
=> Use proper locale inheritance for the base locale

moment.d.ts
The TypeScript typings in 2.14.0 are incorrect and breaking our builds. This should fix the issue.
Thanks for all the hard work ❤️
=> Fix Typings

src/lib/units/month.js, src/locale/lt.js
Reduce `(\s+)+` in RegExp to `(\s)+` to speed them up.
=> Speedup month standalone/format regexes

src/lib/utils/is-number.js
Hi,
We just encountered a bug today where moment was incorrectly parsing year and month fields. The bug was introduced while upgrading to moment v2.16.0.
We eventually tracked it down to another library (modular-scale) which was setting a global variable called `value` to a number. The isNumber function in moment is then mistakenly referencing this global value instead of the input value it gets passed. This pull request fixes the problem.
All the best,
David
=> Fix accidental reference to global "value" variable

src/locale/el.js, src/test/locale/el.js
Bug when calling months from locale data on Greek:
```js
moment.locale('el');
moment.localeData().months(moment());
Uncaught TypeError: Cannot read property 'substring' of undefined
at Locale.months (global.js:6522)
at <anonymous>:1:21
```
Original author @mehiel
=> Fix localeData months call on Greek

package.json
Per rollup & webpack2.
https://github.com/rollup/rollup/wiki/pkg.module
https://webpack.js.org/configuration/resolve/#resolve-mainfields
=> jsnext:main -> module

src/locale/da.js, src/test/locale/da.js
See argumentation at https://github.com/moment/moment/issues/1428#issuecomment-299046240
I kept the zero padding even though DSN says that it's "usually not requried," but it seems to be the way it's done in every other momentjs locale. This way `l` would give the DSN recommended output, while `L` would give one that's close, but has the zero padding. I don't think it would make sense to force those two to be the same. Input welcome if there is a better way to do this.
This is further complicated by the fact that DSN recommends three different formats, `D.M.YYYY`, `D.M.YY` and `YYYY-MM-DD`. I picked the one that is stated to be "traditional" with dots and full year specification.
=> #1428: Updated Danish 'L' dateformat to use dots rather than slashes, aligning with article from DSN.

src/locale/gu.js, src/test/locale/gu.js
Rename newly merged `gu-IN` locale to `gu`.
=> [fixup] Rename gu-IN locale to gu

src/lib/duration/iso-string.js, src/test/moment/duration.js
Avoid a floating-point error during millisecond -> second conversion when formatting duration in ISO format.
Floating-point error is easy to trigger:
```js
console.log(String((123456789 / 1000) % 60));
```
=> Fix #4145: floating-point errors in ISO duration format

src/lib/moment/get-set.js, src/test/moment/getters_setters.js
When changing a year from a random day (not the 29th of february) of a leap year, the day is shifted to the end of the month.
Fixes #4238
=> Fix year setter for random days in leap year

min/moment-with-locales.js, moment.js, src/lib/parse/regex.js
Limiting regex match to 256 chars, fixing #4163.
I did not change the minified versions because I assumed that would be part of some build process and could not find anything about it in "contributing". Please advise if this has to be done manually somehow.
=> [bugfix] Fix for ReDOS vulnerability (see #4163)

src/lib/create/from-array.js, src/test/moment/create.js, src/test/moment/zones.js
#4275 (fix for #4227) but with a few changes:
* Don't create a local date every time, just pull the UTC day out of the UTC-constructed date
* Some more tests
=> [bugfix] Fix weekday verification for UTC and offset days (fixes #4227)

src/moment.js, src/test/moment/format.js
This is an updated version of https://github.com/moment/moment/pull/4009 since it has become stale
fixes https://github.com/moment/moment/issues/3928
Changes:
Added format constants to be used when formatting a moment object to a string that HTML5 input can use, as specified in https://www.w3schools.com/html/html_form_input_types.asp
Supports the following types
- `datetime-local`
- `date`
- `time`
- `week`
- `month`
=> [feature] add format constants to support output to HTML5 input type formats (see #3928)

src/locale/it.js, src/test/locale/it.js
As described in issue #4133, there shouldn't be a comma between weekday and date in Italian locale.
I've checked this by comparing the output of:
```js
Intl.DateTimeFormat("it", {
weekday: "long",
day: "numeric",
month: "long",
year: "numeric",
hour: "2-digit",
minute: "2-digit"
}).format(new Date());
// "sabato 19 agosto 2017, 15:55"
```
(I've not addressed the fact that the browser-native `Intl` implementation puts a comma between the date and time as I'm not sure if moment is trying to mimic `Intl` functionality - and commas in that position are also missing in other locales - e.g. `de`, `en-us`, `en-gb`...)
=> [locale] it: Remove comma between weekday and date, fixes #4133

src/locale/de-ch.js, src/test/locale/de-ch.js
Should be a straight forward update. 
fixes #4189
=> [locale] Fix 4189: Updated time separator for German-Swiss locale

src/locale/ru.js, src/test/locale/ru.js
Simple format change for Russian locale.
=> [locale] Russian LT/LTS: Updated time format in accordance with CLDR and www.timeandunits.com

locale/fr-ca.js, locale/fr-ch.js, locale/fr.js, src/locale/fr-ca.js, src/locale/fr-ch.js, src/locale/fr.js, src/test/locale/fr-ca.js, src/test/locale/fr-ch.js, src/test/locale/fr.js
As discussed in #4038, in french (from France and Belgium anyway, not sure at all about fr-ch and fr-ca), weekdays are written in lowercase.
And having the weekdaysMin capitalise wasn't making any real sense.
=> [locale] set french weekdaysMin in lowercase

src/test/moment/create.js
In `zh-cn` locale (among others) the end of [string with format (timezone offset) unit-test](https://github.com/moment/moment/blob/328d51e7235b7a2d443bfdf69c1844939c115660/src/test/moment/create.js#L357) attempts to create two dates using RFC formatted strings passed to `moment.utc()` with explicit format strings.
This fails because it tries to parse the month and day-of-week using the users locale (`zh-cn`) instead of the English required to parse RFC2822.
This PR removes the locale-specific formatting from the unit-test.
Fixes #4251
=> [bugfix] Fix #4251: Avoid RFC2822 in utc() test

src/lib/moment/format.js, src/test/moment/format.js
A minimal effort to allow users to opt-out of UTC conversion when calling `toISOString()`:
```js
moment().toISOString();
moment().toISOString({ utc: false });
```
Example while running in Europe/London timezone:
```js
moment('2017-07-01').toISOString(); // 2017-06-30T23:00:00.000Z
moment('2017-07-01').toISOString({ utc: false }); // 2017-07-01T00:00:00.000+01:00
```
The PR preserves existing behaviour of converting to UTC by default.
=> [feature] Prevent toISOString converting to UTC (issue #1751)

moment.d.ts
Update the typescript definition file to include the optional parameter keepOffset which was introduced in 2.20.0
@ashsearle @marwahaha
=> [misc] Add optional parameter keepOffset to toISOString

.travis.yml, tasks/transpile.js
The test fails due to we have used deprecated rollup options for a long time and recently rollup 0.53.0 will [throw on unknown options](https://github.com/rollup/rollup/commit/afd30df8a368cec475b9c0265ff1b8812c07891f). Since we always use the latest rollup, the error is thrown as-is.
This PR fixes the issue according to the deprecated warning on the older rollup options.
fixes https://github.com/moment/moment/issues/4373
=> [misc] fix deprecated rollup options

src/lib/locale/locales.js
Right now if the new locale being set is not available then it fails silently and just uses the existing global locale. A console warning would be useful to notify the user of such a failure.
=> [misc] Print console warning when setting non-existent locales

locale/id.js, src/locale/id.js, src/test/locale/id.js
I saw all the other use Agt for august short name. ( like Android iPhone )
=> [locale] id: Fix short name for august in id locale

src/lib/locale/locales.js, src/test/moment/locale_inheritance.js
Fixes #3883. It's currently possible to define a locale with a parent that is not yet defined. However, in the case of this bug when attempting to create a moment using a child locale with a parent that hasn't been loaded yet or hasn't been defined causes an exception to be thrown during prepareConfig.
This fix first attempts to load the parent locale during `defineLocale` if it can't be found initially.  If in the case that a moment is created or a locale is set with a child who's parent can't be loaded or hasn't been defined, `chooseLocale` returns the global locale instead of null. This mitigates the error described in this bug report in the instance the parentLocale can't be located, and follows the same logic when defining a child can't load a parent. I've added a test for this case. …
=> [bugfix] Fix #3883 lazy load parentLocale in defineLocale, fallback to global if missing

moment.d.ts, typing-tests/moment-tests.ts
`min` and `max` only work with moment instances (not Dates, strings, numbers etc.)
Fixes #4316
=> [bugfix] Correct min/max TypeScript signatures

src/lib/moment/format.js
Bug was introduced in PR #4341.
I thought unit-tests using `utc()` and `utcOffset(...)` were good enough, but the behaviour of moments in utc mode isn't the same as non-utc moments with local timezone offsets.
I'm not sure how to create unit-tests for this, but PR continues to keep unit-tests passing, and I've checked behaviour by using this bash script:
```bash
#!/bin/bash
moment=./build/umd/moment.js
for tz in Asia/Kathmandu America/Sao_Paulo Europe/London; do
echo $tz;
TZ=$tz node -e "$(cat << EOF
var moment = require('${moment}');
var m = moment();
console.log(m.toISOString());
console.log(m.toISOString(true));
EOF
)"
done
```
Output:
```
Asia/Kathmandu
2018-01-04T19:06:41.943Z
2018-01-05T00:51:41.943+05:45
America/Sao_Paulo
2018-01-04T19:06:42.071Z
2018-01-04T17:06:42.071-02:00 …
```
=> [bugfix] Fix #4390: use offset properly in toISOString

src/locale/mn.js, src/test/locale/mn.js
Mongolian locale contributing request.
=> [new locale] Added Mongolian locale mn

README.md
👋😃
Noticed that your "npm" badge and "downloads" badge currently both point to the same page on npmjs.org  
I was wondering if you might prefer having the download badge point to a download chart instead?
If not, feel free to close and apologies for the drive-by PR 😄
=> [misc] Update downloads badge to point to graph of downloads 📈

src/locale/zh-tw.js, src/test/locale/zh-tw.js
Properly add spaces between CJK characters and alphanumeric characters in calendar time format.
For @ben-lin and @hehachris
此修改在 Calendar Time 顯示中，在中文字與英數字適當加入空格
「下星期一12:00」->「下星期一` `12:00」
「今天13:00」->「昨天` `13:00」
像是日文 locale 也是相同的格式用法
排版標準：[https://github.com/sparanoid/chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)
舉例來說 Facebook 也是如此顯示
=> [locale] Fix zh-tw locale

moment.d.ts
=> [bugfix] Added HTML5_FMT to moment.d.ts

Gruntfile.js, tasks/qtest.js
I think this will just work. Check out my own Travis Builds and Coveralls here:
https://travis-ci.org/marwahaha/moment/builds
[![Coverage Status](https://coveralls.io/repos/github/marwahaha/moment/badge.svg?branch=add-coveralls)](https://coveralls.io/github/marwahaha/moment?branch=add-coveralls)
Builds are significantly longer (takes ~4 minutes instead of ~3), but the coverage is probably worth it. I sort of prefer long builds to flaky/less-useful builds. (This is why I decided to test twice --- once with `default` and once with coveralls)
this is moment develop's, but it might be out of date
[![Coverage Status](https://coveralls.io/repos/github/moment/moment/badge.svg?branch=develop)](https://coveralls.io/github/moment/moment?branch=develop)
fixes #2509
=> [misc] Add coveralls testing to travis build

src/locale/pt.js, src/test/locale/pt.js
In Portuguese (Portugal) weekdays are in lowercase. So its required that working days will be like `Segunda-feira` not as the actual value `Segunda-Feira`
For those on grammar:
Even the first capital letter is only Ok when in a single word or the first word in a sentence. Regular usage (in the middle of a sentence) it would be all in lowercase.
But we can't control here when it will show one way or the other, so the initial capital letter!
Reference: https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/meses-e-dias-da-semana-outra-vez/3743
=> [locale] pt: Fix capital letters in weekdays

src/lib/units/day-of-week.js, src/test/moment/locale.js
Closes #4347 
This can close #4350 too because this is that change, but with the required unit tests.
=> [bugfix] Treat periods as periods, not regex-anything period, for weekday parsing in strict mode.

src/lib/create/from-string.js
Fixes #4547 - trim() isn't available in old IE / compatibility modes, and moment docs still claim support for IE 8.
=> [bugfix] Avoid using trim()

src/locale/nl-be.js, src/locale/nl.js
**Type**
Bug
**Where?**
Locale nl.js and nl-be.js
**What?**
The month _april_ (April) was two times declared; before and after the month of _mei_ (May) inside monthsRegex regular expression. Next up, inside monthsStrictRegex, the order of months was wrong: april (April) comes after _maart_ (March) and not just before _augustus_ (August).
=> [locale] (nl) order months correctly in regex

src/moment.js, src/test/moment/format.js
Use the ISO WeekYear `GGGG` in HTML5_FMT.WEEK constant.
Updated test cases for the formatting constants to use a date/time that fails with the old `YYYY` format, to prevent regressions.
Fixes #4698 
Fixes #4833
=> [bugfix] Fix #4698: Use ISO WeekYear for HTML5_FMT.WEEK

src/lib/duration/constructor.js, src/test/moment/add_subtract.js
=> [feature] Add support to add/subtract ISO weeks

moment.d.ts, src/lib/moment/compare.js, src/test/moment/is_between.js, typing-tests/moment-tests.ts
Changes to `isBetween` to fix a couple of issues from #4416 and #4114 .
Documentation states that `invalid.isBetween(another, another)` should return `false`, but #4416 highlights a case where it doesn't.  This PR fixes #4416 and ensures `isBetween(..)` return `false` no matter what unit or inclusivity flags are used:
```js
// These should all return false:
invalid.isBetween(another, another);
valid.isBetween(invalid, another);
valid.isBetween(another, invalid);
```
The conversation in #4114 highlights some examples that are incompatible with current typescript bindings.  This PR fixes the typescript binding to match example code - explicitly allowing `null` to be passed in as the `units` value, - and this now follows a faster code path to avoid cloning moments unnecessarily - i.e. fixes …
=> [bugfix] isBetween should return false for invalid dates

src/locale/ky.js, src/test/locale/ky.js
@ichernev @marwahaha 
Fixed small spelling errors in Kyrgyz locale.
[This](https://translate.google.com/#view=home&op=translate&sl=en&tl=ky&text=Yesterday%20morning) and [this](https://translate.google.com/#view=home&op=translate&sl=en&tl=ky&text=Last%20month) are the references from Google Translate for proof :)
=> [locale] ky: Fix spelling typos

package.json, src/lib/duration/humanize.js, src/test/moment/relative_time.js
Added breaking test for multiple relative time thresholds
https://github.com/moment/moment/issues/4909
=> [tests] relative time threshold doesn't work for multiple 

src/lib/duration/as.js, src/lib/duration/prototype.js, src/test/moment/duration.js, src/test/moment/duration_invalid.js
fixes #4886 
Example:
```javascript
moment.duration(6, 'M').as('Q');      // 2
moment.suration(9, 'M').asQuarter();  // 3
```
=> [bugfix] Make Duration#as work with quarters

src/locale/it-ch.js, src/test/locale/it-ch.js
Hi
Similar to #2562, the date format of Swiss Italian should use dots instead of slashes: 14.2.2014 vs 14/2/2014.
The language file is based on the original Italian version.
=> [new locale] Adding Italian (Suisse) it-ch

locale/en-ie.js, src/locale/en-ie.js, src/test/locale/en-ie.js
Correct to en-IE date locale to match the ICU definition: http://www.localeplanet.com/icu/en-IE/index.html
ICU defines the en-IE date format to be 06/11/2018 rather than 06-11-2018.
fixes https://github.com/moment/moment/issues/4857
=> [bugfix] locale/en-ie.js date format

src/locale/es-us.js, src/test/locale/es-us.js
This is the same PR as https://github.com/moment/moment/pull/3894/files, except for the `es-us` locale.
fixes #4162
=> [locale] es-us: Update month parsing to be dot lenient

src/lib/create/date-from-array.js, src/lib/moment/start-end-of.js, src/test/moment/start_end_of.js
These changes to `startOf` and `endOf` fix several DST-related issues:
- avoid using setHours/setMinutes/setSeconds - fixes #1990, fixes #2749, fixes #3580
- use `Date.UTC` / `new Date` for units bigger than hours - fixes #3132, fixes #4152
Additionally, the changes supersede these pull requests: #3620, #4164 and #4254 
Benchmark results
| Benchmark | moment 2.19.3 | this PR | improvement |
| --- | --- | --- | --- |
| startOf second | 2,598,171 ops/sec ±1.24% | 5,322,216 ops/sec ±1.56% | 2.0x |
| startOf minute | 1,606,046 ops/sec ±0.98% | 7,397,801 ops/sec ±0.92% | 4.6x |
| startOf hour | 1,069,176 ops/sec ±0.96% | 5,015,984 ops/sec ±0.91%   | 4.6x |
| startOf date | 811,815 ops/sec ±1.08% | 1,162,031 ops/sec ±0.89%     | 1.4x |
| startOf day | 827,911 ops/sec ±0.83% | 1,170,806 ops/sec …
=> [bugfix] Fix startOf/endOf DST issues while boosting performance

src/locale/ja.js, src/test/locale/ja.js, src/test/moment/start_end_of.js
@baryon 
I just fixed month names.
http://cldr.unicode.org/translation/date-time-patterns
=> [locale] ja: fix long month names

moment.d.ts
We have the ability to update only a single relativeTime handler, but the typescript spec doesn't allow to do so.
Issue ref => https://github.com/moment/moment/issues/4438
=> [bugfix] Fixing RelativeTimeSpec to allow update of a single relativeTime handler

src/lib/units/day-of-week.js, src/locale/en-au.js, src/locale/uk.js, src/test/helpers/common-locale.js, src/test/locale/en-au.js, src/test/locale/en-gb.js
fixes https://github.com/moment/moment/issues/4066
This adds `Locale#weekdays(true)` to sort weekdays by locale (as `moment.weekdays(true)` does if it is the current locale). Same for `#weekdaysShort`, `#weekdaysMin`. 
I added some tests for all locales, and a concrete one for `en-au`.
Example:
```
moment.localeData('en-gb').weekdays(true) 
```
=> [feature] Add localeSort param to Locale weekday methods

src/locale/cs.js, src/test/locale/cs.js
In Czech, it is possible to use also declined form of the month name instead of the nominative case.
This commit adds those declined names of the months.
@radekdostal @marxsk @petrbela - please verify this patch as locales have to be verified by native speakers.
This PR is meant to replace solution suggested in https://github.com/moment/moment/pull/4765 (and agreed with @marxsk in https://github.com/moment/moment/pull/4765#issuecomment-419863315)
*Discussion:*
Pro of this solution is that is it easier to understand because plain regexes or their arrays are used instead of anonymous function.
Con is that "červenec" must precede "červen" in the `monthsRegex` and `monthsStrictRegex` to match properly.
=> [locale] Extend cs locale with name of the months in genitive

src/lib/duration/create.js
The default values of the initialized fields are overwritten in the following lines. This means that the code never relies on the variable defaults.
Removing the unused defaults makes the code easier to read.
=> [misc] Remove unused variable defaults

moment.d.ts, src/locale/pa-in.js, src/test/locale/pa-in.js, src/test/moment/start_end_of.js
You can set `dow` without setting `doy`, so the type should reflect that
=> [misc] Fix type of WeekSpec

src/lib/locale/locales.js, src/test/moment/locale_update.js
`updateLocale(abbr, null)` correctly resets a locale to its previous definition; but didn't check if it needed to reset the 'current' locale'.
This PR fixes that so that resetting the current locale takes immediate effect, without having to manually called `moment.locale(moment.locale())`
Fixes #4962
=> [bugfix] Fix #4962 updateLocale with null to reset

src/locale/es.js, src/test/locale/es.js
=> [locale] es: Add es translation for invalidDate

src/lib/create/from-string.js, src/test/moment/create.js, src/test/moment/duration.js, src/test/moment/is_after.js, src/test/moment/is_before.js, src/test/moment/locale_inheritance.js, src/test/moment/locale_update.js, src/test/moment/weekday.js, src/test/moment/zones.js
that I noticed mostly in tests.
=> [tests] Fix various text typos

src/locale/mr.js, src/test/locale/mr.js
We Marathi people follow standards mentioned below, to label timespans.
Label | Time Span 
------------ | -------------
पहाटे (post midnight, pre-sunrise) |    >= 12am to < 6am 
सकाळी (post sunrise, pre-noon) |    >= 6am to < 12pm
दुपारी (afternoon) |    >= 12pm to < 5pm
सायंकाळी (evening) |    >= 5pm to < 8pm
रात्री (night) |    >= 8pm to < 12am
Actually, 12am is confusing in Marathi tradition. In modern clock system, Moment 12am is considered in arriving date as 0am. And in Marathi tradition it is referred to as final moment of the previous date (Sort of, 0:01 is starting minute of the arriving date) . To comply with modern clock system, I propose to refer to 0am as पहाटे , so that it is considered as moment in the arriving date. Hope this discription itself is not confusing :)
Another …
=> [locale] mr (Marathi)

src/locale/en-sg.js, src/test/locale/en-sg.js
@TechDimension added the locale `en-SG` (#4951). However, it uses a different capitalization from all other locales.
This PR simply renames `en-SG` to `en-sg`. It does not change the actual locale content.
See #5024
=> [locale] (en-sg) Rename locale en-SG to en-sg

src/test/moment/duration.js
`7200000`milliseconds is not `2minutes` but `2hours`.
In the test for `duration`, I fixed a wrong message for the test result about it.
=> [tests] Fix the duration test message

src/locale/en-il.js
In `src/locale/en-li.js`, `ss` is not under `relativeTime`.
So `'%d seconds'` has not been supported yet.
=> [locale] (en-li) Support ss

src/lib/units/timestamp.js
Looks like someone was thinking of parseInt which takes a `radix` param.
In parseFloat there should be one argument only.
=> [misc] Remove stray second arg from `parseFloat`

src/lib/units/offset.js
Remove unnecessary code that rounded off timezone offsets to 15 minute intervals.
This will improve the accuracy of the displayed timezone offset for various dates before countries synchronised clocks properly.
Fixes #5236
=> [bugfix] Support unusual historic timezone offsets (#5236)

package.json
URL is viewable when running `yarn outdated`
=> [misc] Updating to secure URL

src/lib/utils/is-function.js
In some specific context (running js in protected area, in eval conditions), Function might not be available (see / run pastebin here : https://pastebin.com/dPjgkbs9). Therefore, trying to convert unix to isoString will fail with a `TypeError: Right-hand side of 'instanceof' is not an object`.
This PR tries to fix that.
- Added simple Function existance verification in isFunction
Fixes https://github.com/moment/moment/issues/5173.
=> [bugfix] Fixing right-hand instanceof on missing Function

src/locale/nb.js, src/locale/nn.js, src/test/locale/nb.js, src/test/locale/nn.js
The Language Council of Norway has [a list of officially recognized abbreviations](https://www.sprakradet.no/sprakhjelp/Skriveregler/Forkortinger/) for dates, months and weekdays (among other things).
The abbreviations used in momentjs for locales `nn` and `nb` were wrong based on this list, so I took the liberty to update them.
@sigurdga
=> [locale] use correct abbreviations for months and weekdays

src/locale/zh-hk.js, src/test/locale/zh-hk.js
In Hong Kong, `中午` is exactly 1200
References
* `第二節 (上午11時30分至下午1時)` 1130 `上午` https://www.legco.gov.hk/yr18-19/chinese/bc/bc54/agenda/bc5420190427.htm
* `上午11時30分至中午12時` 1200 `中午`  https://www.gov.hk/tc/theme/bf/consultation/10104.htm
* `上 午 9 時 至 下 午 12 時 30 分` 1230 `下午` https://www.immd.gov.hk/hkt/services/travel_document/immigrationoffices.html
=> [locale] Update zh-hk meridiem hour range

src/lib/create/from-object.js, src/test/moment/create.js
As explained in issue #5097  this fixes a bug where `moment({day: 0})` was acting differently from `day: '0'`, `date: 0` or `date: '0'`. This is ultimately due to the use of `i.day || i.date`. When `i.day` is 0, it is still falsey so it returns `i.date` which is undefined. 
This PR makes the behaviour consistent by explicitly checking whether the key is undefined rather than just falsey.
=> [bugfix] Inconsistent moment(object) behaviour when using day: 0 (#5097) 

src/lib/create/from-string-and-array.js, src/test/moment/create.js
Fixes issue in open issue 4435. Test case is based on the example provided there.
https://github.com/moment/moment/issues/4435
=> [bugfix] Invalid parse against array still picks best format. (#4435)

locale/bg.js, src/locale/bg.js, src/test/locale/bg.js
The current translation adds a very specific and mostly unnecessary 'at' in the beginning. It just looks/sounds wrong. Maybe there are cases when this might be correct but surely not most of the time. [insert 'change my mind' meme]
=> [locale] Tweak bg translation for last week

src/locale/ja.js, src/test/locale/ja.js
This reverts commit cf30706573f537b904fd7ee8bf78f8576a45a87e.
@baryon @eternalharvest, [CLDR says](http://cldr.unicode.org/translation/date-time-patterns):
> For some languages, long months are not used; for example, in Japanese the numeric month is used in patterns, in front of the character 月.
Fixes #4965.
=> [locale] Revert "[locale] ja: fix long month names (#4590)"

src/locale/sk.js, src/test/locale/sk.js
"Za" is commonly (and _**incorrectly**_) used to relatively refer to a moment in the future. This error is mainly influenced by Czech language, which is very similar and most Slovaks will understand it, many times domesticating phrases from Czech language. In Czech, "za" is used, though in Slovak, "o" must be used.
Here are references to both "za" and "o" in the official dictionary of Slovak language (_KSSJ_):
https://slovnik.juls.savba.sk/?w=o&s=exact&d=kssj4
https://slovnik.juls.savba.sk/?w=za&s=exact&d=kssj4
And here is a more readable unofficial explanation: https://www.pravopisne.sk/o-hodinu-x-za-hodinu/
...
Okay, so I read the contribution guide that asks to mention the authors of the locale, it appears to me that no one is actualy a Slovak... Anyway... @ichernev, @marwahaha, …
=> [locale] Fix incorrect Slovak translation "za" -> "o"

src/locale/zh-mo.js, src/test/locale/zh-mo.js
This PR is related to #4949, and fixes an error in un-merged PR #4971
=> [new locale] (zh-mo) Add Chinese Macau

src/locale/ro.js, src/test/locale/ro.js
I fixed the abbreviation for the February month in Romanian so that it follows Romanian grammar rules.
Resources where this abbreviation is appearing:
- https://web.library.yale.edu/cataloging/months
- http://abrevierile.ro/colectii/lunile-anului
- https://www.baylor.edu/lib/librarystaff/index.php?id=62713
=> [locale] (ro) Fixed month abbreviation for February

locale/sv.js, src/locale/sv.js, src/test/locale/sv.js
Moment is currently formatting Swedish ordinals incorrectly. Added colon between number and ordinal character.
Ping @ulmus as original author.
Sources:
* https://learningswedish.se/courses/1/pages/ordinal-numbers
* http://swedishbitz.com/ordinal-numbers/
=> [locale] Correct swedish ordinals

src/locale/ar-ma.js, src/test/locale/ar-ma.js
There is a missing point in the arabic name for "Monday"
I didn't check the other arabic locales, but they should be written in the same way.
=> [locale] ar-ma, fix a typo in monday's name

src/lib/create/from-string.js, src/test/moment/create.js
Fixes https://github.com/moment/moment/issues/3918 in it's entirety (support for YYYYMM).
Support for YYYY was added in #4470.
=> [bugfix] Support ISO 8601 YYYYMM format

src/lib/units/week-year.js, src/test/moment/weeks_in_year.js
New Unit Test exemplifies issue in existing version: `weeksInISOYear` assumed that `this.year()` was equal to the moment's ISO year. This is not the case when the new year starts on a Thursday and we are checking the Wednesday (e.g. December 31, 2019 is in ISO year 2020 and ISO year 2020 has 53 weeks)
The Thursday of the week is guaranteed to be in that day's ISO week, so this fix is rather simple.
Closes #3942.
=> [bugfix] Use ISO Year for weeksInISOYear instead of calendar year.

src/lib/locale/locales.js, src/test/moment/locale_update.js
Fixes #5043
There is another PR for the same issue: https://github.com/moment/moment/pull/5044
The problem is the way it is handled. updateLocale was always implemented with the idea that it will handle non-existing locales. It picks the default (base) locale and updates that. The problem was that a name was not set, so after such an update the `locale()` function returned `undefined`.
So the proper fix is to simply set the locale name.
=> [bugfix] Set name when updating non-existent locale

src/locale/ja.js, src/test/locale/ja.js
@caged ichernev
Thank u for merging my PR.
But, since my original PR was written bit long ago, In Japan the era has changed to new 'Reiwa' Era.
So, I need to add new Era definitions for Japanese locale.
This patch fix this issue, and rewrite test cases for this.
I would appreciate if this patch will be merged until next release.
Best, Regards.
#4599 [feature] Add era support for en,ja
=> [locale] ja: Add new 'Reiwa' Era

src/locale/ja.js
As @ichernev is mentioned in PR#5471, the until definition is missing.
So, I wrote this PR to fix this.
This patch just define the last day of 'Heisei' Era in Japanese locale.
Though the result itself is not changed.
=> [locale] ja: Define the last day of 'Heisei' Era

moment.d.ts, ts3.1-typing-tests/moment-tests.ts, ts3.1-typings/moment.d.ts, typing-tests/moment-tests.ts
* This `humanize()` API has added new functions, so it is necessary to update the type definition of `humanize()` synchronously. Fix the compilation and error reporting.
* Fix issue #5524.
=> [bugfix] Update the type definition of the humanize() API, fix compilation error

src/locale/id.js, src/test/locale/id.js
Fixes #5370
Sunday changed to first day of week for Indonesia locale.
Fixes done assuming that doy should be changed to 06, as that is the case for most locales where dow is 0.
=> [locale] id: Sunday changed to first day of week

src/locale/sw.js, src/test/locale/sw.js
It appears that "masiku" does not usually have a plural , going back to "siku" ,
Other prepositions from https://github.com/moment/moment/pull/5544 sounds a bit nice and native,
But, sadly we cannot have them since they are likely to change on future Relative Time , so it is better if they stay that way
fixes https://github.com/moment/moment/issues/5182
=> [locale] (sw) Improve Translation

moment.d.ts
Update moment.d.ts to include 'w' in supported time units.
=> [bugfix] Add 'w' to supported time units.

ts3.1-typing-tests/moment-tests.ts, ts3.1-typings/moment.d.ts, typing-tests/moment-tests.ts
`ts3.1-typing-tests/moment-tests.ts` and `typing-tests/moment-tests.ts`
=> [bugfix] isoWeeksInISOWeekYear in moment.d.ts

src/locale/en-in.js, src/test/locale/en-in.js
@ichernev - following the directions in [previous PR](https://github.com/moment/moment/pull/4626#issuecomment-619652118), I'm updating the en-in locale.
The Indian week starts on a Sunday, and 1st January is the first day of the week. This is the most official source I could find:
https://unicode-org.github.io/cldr-staging/charts/37/supplemental/territory_information.html#IN
If I understand the "Days in week (min)" column, the value of 1 would also mean that the first week would start on 1st Jan, even if it's a Saturday. Am I correct?
=> [locale] Fix Indian week start date and week number

src/locale/ru.js
Only `[ \ ^ $ . | ? * + ( )` need to be escaped, so remove redundant `\` before `]`.
=> [locale] ru: fixes

src/locale/zh-cn.js, src/test/locale/zh-cn.js
This error was introduced by https://github.com/moment/moment/commit/f38d69c3675914442c541c876e116370a731fd40
This PR mostly restore the calendar output to the most common formats, which is almost quite same with what it was before above commit.
This PR passed the test and will fix:
https://github.com/moment/moment/issues/4097
https://github.com/moment/moment/issues/4149
https://github.com/moment/moment/issues/4354
https://github.com/moment/moment/issues/5414 
And you can close other invalid PR like: https://github.com/moment/moment/pull/5357
=> [locale] zh-cn: Improve next/prev week

src/locale/sw.js, src/test/locale/sw.js
Reverting format to the default behaviour as of https://github.com/moment/moment/issues/5366 , using All Caps for AM & PM
=> [locale] (sw) Changed LT to include meridiem

src/locale/fi.js, src/test/locale/fi.js
@bleadof
The fix can probably be understood without understanding the language but mentioning author as per the CONTRIBUTING.md
=> [locale] fi: fix ss not returning the number of seconds

src/locale/it.js, src/test/locale/it.js
I don't know Italian, but this is what my colleague said:
> In Italian, "in" followed by a time expression is translated with "tra", not with "in". 
> There's no difference between "in a day" and "in 1 day" if they are both referred to future plans, they should both be translated with "tra" in Italian.
> "In" in Italian refers to locations. It can also refer to time expressions, but not in the future.
> 
> The current translation is indeed a mistake and it should be changed to
> 
> tra un giorno
> 
> See more info about the use of "in" and "tra" in Italian here (not a complete grammar, of course, but it can give you the idea):
> http://www.italianlanguageguide.com/grammar/prepositions/
=> [locale] it: Improve future relative time

src/locale/az.js, src/test/locale/az.js
@topchiyev 
In Azeri, the word 'bir neçə' should be written separately. Here are some references:
// Wiktionary
https://en.wiktionary.org/wiki/bir_ne%C3%A7%C9%99
// Obastan
https://obastan.com/bir%20ne%C3%A7%C9%99/1010367/?l=az
// Azleks
https://www.azleks.az/online-dictionary/bir+ne%C3%A7%C9%99?s=undefined
=> [locale] az: fix a word

src/locale/gom-deva.js, src/locale/gom-latn.js, src/test/locale/gom-deva.js, src/test/locale/gom-latn.js
Change dow to 0 for Konkani locales to be in line with other Indian locales like en-in and hi, while keeping doy in accordance with ISO 8601.
=> [locale] Update dow for Konkani locales

moment.d.ts, ts3.1-typing-tests/moment-tests.ts, ts3.1-typings/moment.d.ts
=> [bugfix] More complete type definitions for strict formatless parsing #4611

locale/pt-br.js, src/locale/pt-br.js
Hi, I missed this config invalidDate: 'Data inválida' in .../locale/pt-br.js
Tks
=> [locale] (pt-br) add invalid date translation

src/lib/create/from-string.js
If moment is now in maintenance mode, there won't be a major release that removes support for Non RFC2822/ISO date formats.
Given that I've updated the deprecation message to be more accurate. (It may be worth considering not even having the message, given now this behavior will technically be supported by moment forever?)
=> [misc] Update dep message to reflect project status

src/locale/tr.js, src/test/locale/tr.js
=> [locale] tr: update translation of Monday and Saturday

moment.d.ts, ts3.1-typing-tests/moment-tests.ts, ts3.1-typings/moment.d.ts
toArray will always return an array with seven numbers. This change is necessary to be able to do `new Date(...m.toArray())`. As just `number[]`, it complains with `Expected 0-7 arguments, but got 0 or more.`.
=> [misc] Specify length of toArray return type

src/locale/ar-ly.js
The country's English name is [_Libya_](https://en.wikipedia.org/wiki/Libya), not _Lybia_.
=> [locale] ar-ly: fix locale name

src/locale/sr-cyrl.js, src/locale/sr.js, src/test/locale/es-mx.js
PR #5742 added `const` usage that is creating dist files containing ES6 syntax, possibly breaking some environments.
First "bugged" version is 2.29.2. Last working version is 2.29.1.
=> [bugfix] Remove const usage (fixes #5989, #5996)

src/lib/create/from-string.js
Fixes: [#6012](https://github.com/moment/moment/issues/6012)
Using the "look-ahead" mechanism regex in `preprocessRFC2822()` to resolve the problem [Regular Expression Denial of Service (ReDoS)#6012](https://github.com/moment/moment/issues/6012)
=> [bugfix] Fix redos in preprocessRFC2822 regex
